[package]
name = "ascii_image"
version = "0.1.0"
authors = ["kpberry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
bdf = "*"
clap = { version = "*", features = ["derive"] }
log = "*"
env_logger = "*"